pipeline {
    agent any

    tools {
        jdk 'JDK'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
            }
        }

        stage('Build') {
            steps {
                echo 'Compiling Java file...'
                 dir('factorial-app') {
                sh 'javac src/Factorial.java'
                 }
            }
        }

        stage('Run') {
            steps {
                echo 'Running Java program...'
                sh 'java -cp src Factorial'
            }
        }
    }

    post {
        success {
            echo 'Build Successful!'
        }
        failure {
            echo 'Build Failed!'
        }
    }
}