pipeline {
    agent any

    tools {
        jdk 'JDK'
    }

    stages {

        stage('Build') {
            steps {
                echo 'Compiling Java program...'
                dir('factorial-app') {
                    sh '''
                        mkdir -p bin
                        javac -d bin src/Factorial.java
                    '''
                }
            }
        }

        stage('Run') {
            steps {
                echo 'Running Java program...'
                dir('factorial-app') {
                    sh 'java -cp bin Factorial'
                }
            }
        }
    }

    post {
        success {
            echo 'Build Successful!'
        }
        failure {
            echo 'Build Failed!'
        }
    }
}